server:
  port: 8080

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/batisFinal?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      generate-ddl: true
      show-sql: true
