server:
  port: 8083
spring:
  application:
    name: product-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    user: root
    password: 123456
    schemas: productdb
    url: jdbc:mysql://localhost:3306/productdb


