server:
  port: 8081
spring:
  application:
    name: demo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3309/studentDb?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  boot:
    admin:
      client:
        url: http://localhost:9090/


#config eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

#config admin server
management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always

