server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://localhost:8081
          predicates:
            - Path=/demo/**
        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true



