server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3308/orderdb?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true

#config eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true