server:
  port: 9090

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/batisdemo?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      generate-ddl: true
      show-sql: true

python-backend-quantum:
  json-to-qasm: 'http://0.0.0.0:8000/json-to-qasm2'
  qasm-to-json: 'http://0.0.0.0:8000/qasm-to-json2'